//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWebClient.ServiceReferenceEHEC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfWebClient.ServiceReferenceEHEC.Doctor))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.City CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.PatientAtFoodPlace[] PatientAtFoodPlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.Salutation SalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.City City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.PatientAtFoodPlace[] PatientAtFoodPlaces {
            get {
                return this.PatientAtFoodPlacesField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientAtFoodPlacesField, value) != true)) {
                    this.PatientAtFoodPlacesField = value;
                    this.RaisePropertyChanged("PatientAtFoodPlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.Salutation Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNumber {
            get {
                return this.StreetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNumberField, value) != true)) {
                    this.StreetNumberField = value;
                    this.RaisePropertyChanged("StreetNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID {
            get {
                return this.CityIDField;
            }
            set {
                if ((this.CityIDField.Equals(value) != true)) {
                    this.CityIDField = value;
                    this.RaisePropertyChanged("CityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((this.ZipCodeField.Equals(value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class Gender : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenderID {
            get {
                return this.GenderIDField;
            }
            set {
                if ((this.GenderIDField.Equals(value) != true)) {
                    this.GenderIDField = value;
                    this.RaisePropertyChanged("GenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salutation", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class Salutation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalutationIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalutationID {
            get {
                return this.SalutationIDField;
            }
            set {
                if ((this.SalutationIDField.Equals(value) != true)) {
                    this.SalutationIDField = value;
                    this.RaisePropertyChanged("SalutationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doctor", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class Doctor : WpfWebClient.ServiceReferenceEHEC.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoctorIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoctorID {
            get {
                return this.DoctorIDField;
            }
            set {
                if ((this.DoctorIDField.Equals(value) != true)) {
                    this.DoctorIDField = value;
                    this.RaisePropertyChanged("DoctorID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientAtFoodPlace", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class PatientAtFoodPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.FoodPlace FoodPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoodPlaceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.Person PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VistingDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.FoodPlace FoodPlace {
            get {
                return this.FoodPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodPlaceField, value) != true)) {
                    this.FoodPlaceField = value;
                    this.RaisePropertyChanged("FoodPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodPlaceID {
            get {
                return this.FoodPlaceIDField;
            }
            set {
                if ((this.FoodPlaceIDField.Equals(value) != true)) {
                    this.FoodPlaceIDField = value;
                    this.RaisePropertyChanged("FoodPlaceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.Person Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientID {
            get {
                return this.PatientIDField;
            }
            set {
                if ((this.PatientIDField.Equals(value) != true)) {
                    this.PatientIDField = value;
                    this.RaisePropertyChanged("PatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VistingDate {
            get {
                return this.VistingDateField;
            }
            set {
                if ((this.VistingDateField.Equals(value) != true)) {
                    this.VistingDateField = value;
                    this.RaisePropertyChanged("VistingDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((this.CountryIDField.Equals(value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodPlace", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class FoodPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.City CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoodPlaceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.PatientAtFoodPlace[] PatientAtFoodPlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetnumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.City City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodPlaceID {
            get {
                return this.FoodPlaceIDField;
            }
            set {
                if ((this.FoodPlaceIDField.Equals(value) != true)) {
                    this.FoodPlaceIDField = value;
                    this.RaisePropertyChanged("FoodPlaceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.PatientAtFoodPlace[] PatientAtFoodPlaces {
            get {
                return this.PatientAtFoodPlacesField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientAtFoodPlacesField, value) != true)) {
                    this.PatientAtFoodPlacesField = value;
                    this.RaisePropertyChanged("PatientAtFoodPlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Streetname {
            get {
                return this.StreetnameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetnameField, value) != true)) {
                    this.StreetnameField = value;
                    this.RaisePropertyChanged("Streetname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Streetnumber {
            get {
                return this.StreetnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetnumberField, value) != true)) {
                    this.StreetnumberField = value;
                    this.RaisePropertyChanged("Streetnumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exam", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class Exam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.Doctor DoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.Person PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfWebClient.ServiceReferenceEHEC.Strain StrainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.Doctor Doctor {
            get {
                return this.DoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorField, value) != true)) {
                    this.DoctorField = value;
                    this.RaisePropertyChanged("Doctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamID {
            get {
                return this.ExamIDField;
            }
            set {
                if ((this.ExamIDField.Equals(value) != true)) {
                    this.ExamIDField = value;
                    this.RaisePropertyChanged("ExamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.Person Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfWebClient.ServiceReferenceEHEC.Strain Strain {
            get {
                return this.StrainField;
            }
            set {
                if ((object.ReferenceEquals(this.StrainField, value) != true)) {
                    this.StrainField = value;
                    this.RaisePropertyChanged("Strain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Strain", Namespace="http://schemas.datacontract.org/2004/07/Server.Models")]
    [System.SerializableAttribute()]
    public partial class Strain : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrainIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StrainID {
            get {
                return this.StrainIDField;
            }
            set {
                if ((this.StrainIDField.Equals(value) != true)) {
                    this.StrainIDField = value;
                    this.RaisePropertyChanged("StrainID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEHEC.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WritePatient", ReplyAction="http://tempuri.org/IService/WritePatientResponse")]
        void WritePatient(WpfWebClient.ServiceReferenceEHEC.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WritePatient", ReplyAction="http://tempuri.org/IService/WritePatientResponse")]
        System.Threading.Tasks.Task WritePatientAsync(WpfWebClient.ServiceReferenceEHEC.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteExam", ReplyAction="http://tempuri.org/IService/WriteExamResponse")]
        void WriteExam(WpfWebClient.ServiceReferenceEHEC.Exam exam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteExam", ReplyAction="http://tempuri.org/IService/WriteExamResponse")]
        System.Threading.Tasks.Task WriteExamAsync(WpfWebClient.ServiceReferenceEHEC.Exam exam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteCity", ReplyAction="http://tempuri.org/IService/WriteCityResponse")]
        void WriteCity(WpfWebClient.ServiceReferenceEHEC.City city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteCity", ReplyAction="http://tempuri.org/IService/WriteCityResponse")]
        System.Threading.Tasks.Task WriteCityAsync(WpfWebClient.ServiceReferenceEHEC.City city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteCountry", ReplyAction="http://tempuri.org/IService/WriteCountryResponse")]
        void WriteCountry(WpfWebClient.ServiceReferenceEHEC.Country country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteCountry", ReplyAction="http://tempuri.org/IService/WriteCountryResponse")]
        System.Threading.Tasks.Task WriteCountryAsync(WpfWebClient.ServiceReferenceEHEC.Country country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteFoodPlace", ReplyAction="http://tempuri.org/IService/WriteFoodPlaceResponse")]
        void WriteFoodPlace(WpfWebClient.ServiceReferenceEHEC.FoodPlace foodplace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteFoodPlace", ReplyAction="http://tempuri.org/IService/WriteFoodPlaceResponse")]
        System.Threading.Tasks.Task WriteFoodPlaceAsync(WpfWebClient.ServiceReferenceEHEC.FoodPlace foodplace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGenders", ReplyAction="http://tempuri.org/IService/GetGendersResponse")]
        WpfWebClient.ServiceReferenceEHEC.Gender[] GetGenders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGenders", ReplyAction="http://tempuri.org/IService/GetGendersResponse")]
        System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Gender[]> GetGendersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSalutations", ReplyAction="http://tempuri.org/IService/GetSalutationsResponse")]
        WpfWebClient.ServiceReferenceEHEC.Salutation[] GetSalutations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSalutations", ReplyAction="http://tempuri.org/IService/GetSalutationsResponse")]
        System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Salutation[]> GetSalutationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStrains", ReplyAction="http://tempuri.org/IService/GetStrainsResponse")]
        WpfWebClient.ServiceReferenceEHEC.Strain[] GetStrains();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStrains", ReplyAction="http://tempuri.org/IService/GetStrainsResponse")]
        System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Strain[]> GetStrainsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDoctors", ReplyAction="http://tempuri.org/IService/GetDoctorsResponse")]
        WpfWebClient.ServiceReferenceEHEC.Doctor[] GetDoctors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDoctors", ReplyAction="http://tempuri.org/IService/GetDoctorsResponse")]
        System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Doctor[]> GetDoctorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCities", ReplyAction="http://tempuri.org/IService/GetCitiesResponse")]
        WpfWebClient.ServiceReferenceEHEC.City[] GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCities", ReplyAction="http://tempuri.org/IService/GetCitiesResponse")]
        System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.City[]> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCountries", ReplyAction="http://tempuri.org/IService/GetCountriesResponse")]
        WpfWebClient.ServiceReferenceEHEC.Country[] GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCountries", ReplyAction="http://tempuri.org/IService/GetCountriesResponse")]
        System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Country[]> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFoodPlaces", ReplyAction="http://tempuri.org/IService/GetFoodPlacesResponse")]
        WpfWebClient.ServiceReferenceEHEC.FoodPlace[] GetFoodPlaces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFoodPlaces", ReplyAction="http://tempuri.org/IService/GetFoodPlacesResponse")]
        System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.FoodPlace[]> GetFoodPlacesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRelations", ReplyAction="http://tempuri.org/IService/GetRelationsResponse")]
        WpfWebClient.ServiceReferenceEHEC.PatientAtFoodPlace[] GetRelations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRelations", ReplyAction="http://tempuri.org/IService/GetRelationsResponse")]
        System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.PatientAtFoodPlace[]> GetRelationsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WpfWebClient.ServiceReferenceEHEC.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WpfWebClient.ServiceReferenceEHEC.IService>, WpfWebClient.ServiceReferenceEHEC.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WritePatient(WpfWebClient.ServiceReferenceEHEC.Person person) {
            base.Channel.WritePatient(person);
        }
        
        public System.Threading.Tasks.Task WritePatientAsync(WpfWebClient.ServiceReferenceEHEC.Person person) {
            return base.Channel.WritePatientAsync(person);
        }
        
        public void WriteExam(WpfWebClient.ServiceReferenceEHEC.Exam exam) {
            base.Channel.WriteExam(exam);
        }
        
        public System.Threading.Tasks.Task WriteExamAsync(WpfWebClient.ServiceReferenceEHEC.Exam exam) {
            return base.Channel.WriteExamAsync(exam);
        }
        
        public void WriteCity(WpfWebClient.ServiceReferenceEHEC.City city) {
            base.Channel.WriteCity(city);
        }
        
        public System.Threading.Tasks.Task WriteCityAsync(WpfWebClient.ServiceReferenceEHEC.City city) {
            return base.Channel.WriteCityAsync(city);
        }
        
        public void WriteCountry(WpfWebClient.ServiceReferenceEHEC.Country country) {
            base.Channel.WriteCountry(country);
        }
        
        public System.Threading.Tasks.Task WriteCountryAsync(WpfWebClient.ServiceReferenceEHEC.Country country) {
            return base.Channel.WriteCountryAsync(country);
        }
        
        public void WriteFoodPlace(WpfWebClient.ServiceReferenceEHEC.FoodPlace foodplace) {
            base.Channel.WriteFoodPlace(foodplace);
        }
        
        public System.Threading.Tasks.Task WriteFoodPlaceAsync(WpfWebClient.ServiceReferenceEHEC.FoodPlace foodplace) {
            return base.Channel.WriteFoodPlaceAsync(foodplace);
        }
        
        public WpfWebClient.ServiceReferenceEHEC.Gender[] GetGenders() {
            return base.Channel.GetGenders();
        }
        
        public System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Gender[]> GetGendersAsync() {
            return base.Channel.GetGendersAsync();
        }
        
        public WpfWebClient.ServiceReferenceEHEC.Salutation[] GetSalutations() {
            return base.Channel.GetSalutations();
        }
        
        public System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Salutation[]> GetSalutationsAsync() {
            return base.Channel.GetSalutationsAsync();
        }
        
        public WpfWebClient.ServiceReferenceEHEC.Strain[] GetStrains() {
            return base.Channel.GetStrains();
        }
        
        public System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Strain[]> GetStrainsAsync() {
            return base.Channel.GetStrainsAsync();
        }
        
        public WpfWebClient.ServiceReferenceEHEC.Doctor[] GetDoctors() {
            return base.Channel.GetDoctors();
        }
        
        public System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Doctor[]> GetDoctorsAsync() {
            return base.Channel.GetDoctorsAsync();
        }
        
        public WpfWebClient.ServiceReferenceEHEC.City[] GetCities() {
            return base.Channel.GetCities();
        }
        
        public System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.City[]> GetCitiesAsync() {
            return base.Channel.GetCitiesAsync();
        }
        
        public WpfWebClient.ServiceReferenceEHEC.Country[] GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.Country[]> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public WpfWebClient.ServiceReferenceEHEC.FoodPlace[] GetFoodPlaces() {
            return base.Channel.GetFoodPlaces();
        }
        
        public System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.FoodPlace[]> GetFoodPlacesAsync() {
            return base.Channel.GetFoodPlacesAsync();
        }
        
        public WpfWebClient.ServiceReferenceEHEC.PatientAtFoodPlace[] GetRelations() {
            return base.Channel.GetRelations();
        }
        
        public System.Threading.Tasks.Task<WpfWebClient.ServiceReferenceEHEC.PatientAtFoodPlace[]> GetRelationsAsync() {
            return base.Channel.GetRelationsAsync();
        }
    }
}
